# This is a basic workflow to help you get started with Actions

name: Update README.md

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  schedule:
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          python -m pip install feedparser
     # Runs a single command using the runners shell
      - name: Update README
        run: python update.py

      # Runs a set of commands using the runners shell
      - name: Commit and push if changed
        run: |
            git diff
            git config --global user.email "orzlee@test.com"
            git config --global user.name "OrLee"
            git pull
            git add -A
            git commit -m "Updated content" || exit 0
            git push
